Revert "Add img2simg tool that splits a large image into <n> sparse files"
This reverts commit dba7d246a20d14663c2e90b2fa9051894e3c7e1b

Broke the build:
system/extras/ext4_utils/img2simg.c:23:20: error: endian.h: No such file or directory
system/extras/ext4_utils/img2simg.c: In function ‘main’:
system/extras/ext4_utils/img2simg.c:262: warning: implicit declaration of function ‘htole32’
system/extras/ext4_utils/img2simg.c:263: warning: implicit declaration of function ‘htole16’
make: * [out/host/darwin-x86/obj/EXECUTABLES/img2simg_intermediates/img2simg.o] Error 1